### ISSUE TITLE
improvements added

### ISSUE THREAD

**Issue by 9ahmed** [Abb1x/dotfiles#2]
https://github.com/Abb1x/dotfiles/blob/e7cb6398e05d11177da977e0e95a5b77e2aa0e3f/autostart.sh#L50

please add roundness on the panel in autostart.sh

**Comment by Abb1x** [comment]
I don't see any improvements? What do you mean?

**Comment by 9ahmed** [comment]
add improvments

**Comment by Abb1x** [comment]
what's the point of "Improvements added" then?

**Comment by 9ahmed** [comment]
its a typo

**Comment by Abb1x** [comment]
Issue closed as useless
